#!/bin/bash

# This script checks if an existing QHOME environment was configured
# If so, it points the envvars to the conda q installation
. ./resetqenv

export QPORT=5000
export CBPRO_ENV="dev"
export CBPRO_PRIV_KEY=""
export CBPRO_PRIV_SECRET=""
export CBPRO_PRIV_PASSPHRASE=""

q -p $QPORT
